namespace :db do
  desc "Fill database with NFL team data"
  task populate_teams: :environment do
  	Team.create!(location: "Dallas",
				 nickname: "Cowboys",
				 division: "NFC East",
				 coach: "Jason Garrett",
				 wins_2011: 8,
				 losses_2011: 8,
				 wins_2012: 0,
				 losses_2012: 0)
  	Team.create!(location: "New York",
				 nickname: "Giants",
				 division: "NFC East",
				 coach: "Tom Coughlin",
				 wins_2011: 9,
				 losses_2011: 7,
				 wins_2012: 0,
				 losses_2012: 0)
	Team.create!(location: "Philadelphia",
				 nickname: "Eagles",
				 division: "NFC East",
				 coach: "Andy Reid",
				 wins_2011: 8,
				 losses_2011: 8,
				 wins_2012: 0,
				 losses_2012: 0)
	Team.create!(location: "Washington",
				 nickname: "Redskins",
				 division: "NFC East",
				 coach: "Mike Shanahan",
				 wins_2011: 5,
				 losses_2011: 11,
				 wins_2012: 0,
				 losses_2012: 0)
	Team.create!(location: "Arizona",
				 nickname: "Cardinals",
				 division: "NFC West",
				 coach: "Ken Whisenhunt",
				 wins_2011: 8,
				 losses_2011: 8,
				 wins_2012: 0,
				 losses_2012: 0)
	Team.create!(location: "San Francisco",
				 nickname: "49ers",
				 division: "NFC West",
				 coach: "Jim Harbaugh",
				 wins_2011: 13,
				 losses_2011: 3,
				 wins_2012: 0,
				 losses_2012: 0)
	Team.create!(location: "Seattle",
				 nickname: "Seahawks",
				 division: "NFC West",
				 coach: "Pete Carroll",
				 wins_2011: 7,
				 losses_2011: 9,
				 wins_2012: 0,
				 losses_2012: 0)
	Team.create!(location: "St. Louis",
				 nickname: "Rams",
				 division: "NFC West",
				 coach: "Jeff Fisher",
				 wins_2011: 2,
				 losses_2011: 14,
				 wins_2012: 0,
				 losses_2012: 0)
	Team.create!(location: "Chicago",
				 nickname: "Bears",
				 division: "NFC North",
				 coach: "Lovie Smith",
				 wins_2011: 8,
				 losses_2011: 8,
				 wins_2012: 0,
				 losses_2012: 0)
	Team.create!(location: "Detroit",
				 nickname: "Lions",
				 division: "NFC North",
				 coach: "Jim Schwartz",
				 wins_2011: 10,
				 losses_2011: 6,
				 wins_2012: 0,
				 losses_2012: 0)
	Team.create!(location: "Green Bay",
				 nickname: "Packers",
				 division: "NFC North",
				 coach: "Mike McCarthy",
				 wins_2011: 15,
				 losses_2011: 1,
				 wins_2012: 0,
				 losses_2012: 0)
	Team.create!(location: "Minnesota",
				 nickname: "Vikings",
				 division: "NFC North",
				 coach: "Leslie Frazier",
				 wins_2011: 3,
				 losses_2011: 13,
				 wins_2012: 0,
				 losses_2012: 0)
	end
end
